image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out/
  only:
    - main

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r out/* public/
  artifacts:
    paths:
      - public
  only:
    - main